config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :flowdock_settings, only: [:update, :edit]
  end
end

app/models/spree/flowdock_configuration.rb
class Spree::FlowdockConfiguration < Spree::Preferences::Configuration
  preference :api_token_order_confirmation, :string, default: ''
  preference :api_token_inbox_message, :string, default: ''
end

app/models/spree/flowdock_inbox_message.rb
require 'flowdock'

module Spree
  class FlowdockInboxMessage

    attr_reader :flow, :message, :type

    def initialize(message, type = :info)
      raise ArgumentError.new('Message missing.') if message.blank?

      @flow = flow
      @message = message
      @type = type
    end

    def push
      return false if @flow.nil?
      # send message to Team Inbox
      @flow.push_to_team_inbox(
        subject: subject,
        content: content,
        tags: tags,
        link: link
      )
    end

    private

    def flow
      if api_token.blank?
        Rails.logger.error "Flowdock API token is not configured."
        return nil
      end
      # create a new Flow object with target flow's api token and sender information for Team Inbox posting
      Flowdock::Flow.new(api_token: api_token, source: source, from: { name: name, address: address })
    end

    def api_token
      @_api_token ||= configured_token
    end

    def flowdock_configuration
      @_configuration ||= Spree::FlowdockConfiguration.new
    end

    def current_store
      @_store ||= Spree::Store.current(Rails.env)
    end

    def source
      current_store.name ||= Rails.application.class.parent_name
    end

    def name
      source
    end

    def address
      current_store.mail_from_address ||= 'spree@example.com'
    end

    # Override the following methods in child classes

    def subject
      I18n.t('flowdock.inbox_message.subject', message_type: I18n.t("flowdock.inbox_message.type.#{@type}"), store_name: current_store.name)
    end

    def content
      @message
    end

    def tags
      [Rails.env, @type.to_s, 'message']
    end

    def link
      "#{current_store.url}"
    end

    def configured_token
      flowdock_configuration.api_token_inbox_message
    end
  end
end

app/models/spree/flowdock_order_confirmation.rb
require 'flowdock'

module Spree
  class FlowdockOrderConfirmation < FlowdockInboxMessage

    attr_reader :order

    def initialize(order)
      raise ArgumentError.new('Order missing.') if order.blank?

      @flow = flow
      @order = order
    end

    private

    def subject
      I18n.t('flowdock.order.confirmation.subject', store_name: current_store.name)
    end

    def content
      I18n.t('flowdock.order.confirmation.content_html', order_number: @order.number, order_total: @order.display_total)
    end

    def tags
      [Rails.env, 'order', 'incoming', @order.number]
    end

    def link
      "#{current_store.url}/de/admin/orders/#{@order.number}/edit"
    end

    def configured_token
      flowdock_configuration.api_token_order_confirmation
    end
  end
end

app/controllers/spree/admin/flowdock_settings_controller.rb
module Spree
  module Admin
    class FlowdockSettingsController < Spree::Admin::BaseController

      def edit
        @config = Spree::FlowdockConfiguration.new
      end

      def update
        save_settings(params[:preferences])
        redirect_to edit_admin_flowdock_settings_path
      end

      private

      def save_settings(values)
        config = Spree::FlowdockConfiguration.new
        values.each do |name, value|
          next unless config.has_preference? name
          config[name] = value
        end
      end

    end
  end
end

app/controllers/spree/orders_controller_decorator.rb
Spree::OrdersController.class_eval do
  after_filter :push_order_confirmation, only: [:show]

  private

  def push_order_confirmation
    if flash[:order_completed] && @order.present?
      Spree::FlowdockOrderConfirmation.new(@order).push
    end
  end

end

app/views/spree/admin/flowdock_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= t('flowdock.settings.title') %>
<% end %>

<%= form_for(@config, :as => "flowdock_configuration", :url => admin_flowdock_settings_path, :method => :put) do |form| %>
  <div id="preferences" data-hook>
      <fieldset class="general no-border-top">
        <div class="row">
          <div class="col-md-6">
            <div class="panel panel-default security">
              <div class="panel-heading">
                <h1 class="panel-title">
                  <%= t('flowdock.settings.api_tokens') %>
                </h1>
              </div>
              <div class="panel-body">
                <div class="form-group">
                  <%= label_tag("preferences[api_token_order_confirmation]", t('flowdock.order.confirmation.api_token')) %>
                  <%= preference_field_tag("preferences[api_token_order_confirmation]", @config[:api_token_order_confirmation], :type => :string) %>
                </div>
                <div class="form-group">
                  <%= label_tag("preferences[api_token_inbox_message]", t('flowdock.inbox_message.api_token')) %>
                  <%= preference_field_tag("preferences[api_token_inbox_message]", @config[:api_token_inbox_message], :type => :string) %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="form-actions" data-hook="buttons">
          <%= button Spree.t('actions.update'), 'save' %>
        </div>
      </fieldset>
  </div>
<% end %>